version: '3.1'

services:
  pentaho_server:
    container_name: pentaho-server
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DOCKER_PENTAHO_REPOSITORY=postgresql
      - DOCKER_PENTAHO_POSTGRES_HIBERNATE_URL=jdbc:postgresql://db:5432/hibernate
      - DOCKER_PENTAHO_POSTGRES_HIBERNATE_USERNAME=hibuser
      - DOCKER_PENTAHO_POSTGRES_HIBERNATE_PASSWORD=password
      - DOCKER_PENTAHO_POSTGRES_QUARTZ_URL=jdbc:postgresql://db:5432/quartz
      - DOCKER_PENTAHO_POSTGRES_QUARTZ_USERNAME=pentaho_user
      - DOCKER_PENTAHO_POSTGRES_QUARTZ_PASSWORD=password
      - DOCKER_PENTAHO_POSTGRES_JACKRABBIT_URL=jdbc:postgresql://db:5432/jackrabbit
      - DOCKER_PENTAHO_POSTGRES_JACKRABBIT_USERNAME=jcr_user
      - DOCKER_PENTAHO_POSTGRES_JACKRABBIT_PASSWORD=password
      - DOCKER_PENTAHO_CORS_ALLOWED_DOMAINS=http://lotfi-dev-env.francecentral.cloudapp.azure.com:8081
      - DOCKER_PENTAHO_TOMCAT_PROXY_PORT=8081
      - DOCKER_PENTAHO_TOMCAT_PROXY_NAME=lotfi-dev-env.francecentral.cloudapp.azure.com
      - DOCKER_PENTAHO_TOMCAT_PROXY_SCHEME=http
      - DOCKER_PENTAHO_AUTH_MODE=saml
      - DOCKER_PENTAHO_LDAP_ROLE_ATTRIBUTE=employeeType
      - DOCKER_PENTAHO_IDP_URL=http://lotfi-dev-env.francecentral.cloudapp.azure.com:8443/simplesaml/saml2/idp/metadata.php
      - DOCKER_PENTAHO_KESTORE_PASSWORD=nalle123
      - DOCKER_PENTAHO_KEYSTORE_USERNAME_PASSWORDS=apollo:nalle123,apollo01:nalle01
      - "DOCKER_PENTAHO_KEYSTORE_USERNAME_PASSWORD_DELIMITER=:"
      - DOCKER_PENTAHO_KEYSTORE_DEFAULT_KEY=apollo
      - |
        DOCKER_PENTAHO_IDP_CERT=
        -----BEGIN CERTIFICATE-----

        -----END CERTIFICATE-----
    ports:
      - 8081:8080
    volumes:
      - ./pentaho-server:/home/pentaho/pentaho-server
      - ./entrypoint:/home/pentaho/entrypoint
      - ./entrypoint/templates/saml/metadata:/home/pentaho/pentaho-server/pentaho-solutions/metadata/
    depends_on:
      - db
  db:
    container_name: pentaho-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: pentaho-adminer
    image: adminer
    restart: always
    ports:
      - 8888:8080
  ########################
  #### AUTHENTICATION ####
  ########################
  ldap-openldap:
    container_name: "ldap-openldap"
    image: osixia/openldap:1.2.5
    environment: # using an .env file here seems to break things.
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "3S"
      LDAP_DOMAIN: "pentaho.fr"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_ENFORCE: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_RFC2307BIS_SCHEMA: "true"
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "pentaho.fr"

  ldapadmin:
    image: suezenv/phpldapadmin-docker
    container_name: "pentaho_ldapadmin"
    environment: # using an .env file here seems to break things.
      LDAP_URL: "ldap-openldap"
      LDAP_BASE: "dc=pentaho,dc=fr"
      LDAP_ADMIN: "cn=admin,dc=pentaho,dc=fr"
    volumes:
      - ./phpldapadmin/templates/creation:/etc/phpldapadmin/templates/creation
    ports:
      - "8080:80"
    depends_on:
      - ldap-openldap

  pentaho-idp:
    container_name: 'pentaho_idp'
    image: 'suezenv/simplesamlphp:latest'
    ports:
      - '8443:80'
    volumes:
        - './simplesamlphp/certs:/var/simplesamlphp/cert/'
        #- './simplesamlphp/design/modules/suez/default-enable:/var/simplesamlphp/modules/suez/default-enable'
        #- './simplesamlphp/design/modules/suez/www/static/media/sludge/bgHome.png:/var/simplesamlphp/modules/suez/www/static/media/sludge/bgHome.png'
        #- './simplesamlphp/design/modules/suez/themes/sludge/core/loginuserpass.twig:/var/simplesamlphp/modules/suez/themes/sludge/core/loginuserpass.twig'
        #- './simplesamlphp/design/modules/suez/themes/sludge/core/suez_base.twig:/var/simplesamlphp/modules/suez/themes/sludge/core/suez_base.twig'
        #- './simplesamlphp/design/modules/suez/themes/sludge/default/base.twig:/var/simplesamlphp/modules/suez/themes/sludge/default/base.twig'
        #- './simplesamlphp/design/modules/suez/themes/sludge/default/style.css.twig:/var/simplesamlphp/modules/suez/themes/sludge/default/style.css.twig'
        - './simplesamlphp/var-simplesamlphp/metadata/saml20-sp-remote.php:/var/simplesamlphp/metadata/saml20-sp-remote.php'
        - './simplesamlphp/var-simplesamlphp/metadata/saml20-idp-hosted.php:/var/simplesamlphp/metadata/saml20-idp-hosted.php'
        - './simplesamlphp/var-simplesamlphp/config/authsources.php:/var/simplesamlphp/config/authsources.php'
        - './simplesamlphp/var-simplesamlphp/config/config.php:/var/simplesamlphp/config/config.php'
        - './simplesamlphp/etc-httpd/conf.d/ssp.conf:/etc/httpd/conf.d/ssp.conf'
    links:
      - 'ldap-openldap'

